GerenciamentoBovinos/Models/Veterinario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GerenciamentoBovinos.Models
{
    public class Veterinario : Pessoa
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [MaxLength(30, ErrorMessage = "O {0} deve ter no máximo {1} caracteres")]
        public string CRMV { get; set; }
    }
}

GerenciamentoBovinos/Controllers/VeterinarioController.cs
using GerenciamentoBovinos.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GerenciamentoBovinos.Controllers
{
    [Authorize(Roles = "Sistema,Administrativo")]
    public class VeterinarioController : Controller
    {
        private GerenciamentoContext db = new GerenciamentoContext();

        // GET: Veterinario
        /// <summary>
        /// Retorna a lista de veterinários cadastrados
        /// </summary>
        /// <param name="retorno"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Index(string retorno = null)
        {
            ViewBag.Retorno = retorno;
            return View(db.Veterinarios.ToList());
        }

        // GET: Veterinario/Create
        /// <summary>
        /// Gera a view para cadastrar um veterinário
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Create()
        {
            return View();
        }

        // POST: Veterinario/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Adiciona um veterinário
        /// </summary>
        /// <param name="veterinario"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,InscricaoEstadual,CRMV,Nome,Email,Telefone,Rua,Numero,Estado,Cidade,Cep,Complemento,CPFCNPJ")] Veterinario veterinario)
        {
            if (ModelState.IsValid)
            {
                db.Veterinarios.Add(veterinario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(veterinario);
        }

        // GET: Veterinario/Edit/5
        /// <summary>
        /// Gera a view para editar um veterinário
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veterinario veterinario = db.Veterinarios.Find(id);
            if (veterinario == null)
            {
                return HttpNotFound();
            }
            return View(veterinario);
        }

        // POST: Veterinario/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edita um veterinário
        /// </summary>
        /// <param name="veterinario"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,InscricaoEstadual,CRMV,Nome,Email,Telefone,Rua,Numero,Estado,Cidade,Cep,Complemento,CPFCNPJ")] Veterinario veterinario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(veterinario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(veterinario);
        }

        // GET: Bovino/Delete/5
        /// <summary>
        /// Exclui um veterinário
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Delete(long? id)
        {
            Veterinario veterinario = db.Veterinarios.Find(id);

            List<Consulta> listaAtendimento = db.Consultas.Where(x => x.VeterinarioId == id).ToList();

            if (listaAtendimento != null && listaAtendimento.Count > 0)
            {
                return RedirectToAction("Index", new { retorno = "Este Veterinário esta relacionado a algum atendimento cadastrado!" });
            }

            if (veterinario != null)
            {
                db.Veterinarios.Remove(veterinario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return new HttpNotFoundResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GerenciamentoBovinos/Views/Veterinario/Create.cshtml
@model GerenciamentoBovinos.Models.Veterinario

@{
    ViewBag.Title = "Cadastrar Veterinario";
}

<h2 class="text-center">Cadastrar Veterinário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.CRMV, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.CRMV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CRMV, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.CPFCNPJ, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.CPFCNPJ, new { @class = "form-control", @name = "cpfcnpj", onkeypress = "mascaraMutuario(this,cpfCnpj)", onblur = "clearTimeout()", maxlength = "18" })
                @Html.ValidationMessageFor(model => model.CPFCNPJ, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control", @name = "telefone", onkeypress = "mascara(this, mtel)", onblur = "clearTimeout()", maxlength = "14" })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Rua, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Rua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-1">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.Cep, new { @class = "form-control", @name = "cep", onkeypress = "mascara(this, mcep)", onblur = "clearTimeout()", maxlength = "9" })
                @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextAreaFor(model => model.Complemento, new { @class = "col-md-12 form-control", rows = "4" })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

GerenciamentoBovinos/Views/Veterinario/Edit.cshtml
@model GerenciamentoBovinos.Models.Veterinario

@{
    ViewBag.Title = "Editar Veterinário";
}

<h2 class="text-center">Editar Veterinário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.CRMV, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.CRMV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CRMV, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.CPFCNPJ, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.CPFCNPJ, new { @class = "form-control", @name = "cpfcnpj", onkeypress = "mascaraMutuario(this,cpfCnpj)", onblur = "clearTimeout()", maxlength = "18" })
                @Html.ValidationMessageFor(model => model.CPFCNPJ, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control", @name = "telefone", onkeypress = "mascara(this, mtel)", onblur = "clearTimeout()", maxlength = "14" })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Rua, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Rua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-1">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.Cep, new { @class = "form-control", @name = "cep", onkeypress = "mascara(this, mcep)", onblur = "clearTimeout()", maxlength = "9" })
                @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextAreaFor(model => model.Complemento, new { @class = "col-md-12 form-control", rows = "4" })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

GerenciamentoBovinos/Views/Veterinario/Index.cshtml
@model IEnumerable<GerenciamentoBovinos.Models.Veterinario>

@{
    ViewBag.Title = "Lista de Veterinários";
    string retornoDelete = ViewBag.Retorno;
}

<h2 class="text-center">Lista de Veterinarios</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-secondary" })
</p>

<p class="text-danger" id="retorno">@retornoDelete</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CPFCNPJ)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CRMV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.Raw("Ações")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPFCNPJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CRMV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Veterinario", new { id = item.Id})">
                    <i class="fa fa-pencil-square-o fa-2x"></i>
                </a>
                <a id="deleteItem" class="deleteItem ml-2" href="#" style="color:red" data-target="#myModal" data-toggle="modal" data-path="@Url.Action("Delete", "Veterinario", new { id = @item.Id })">
                    <i class="fa fa-trash-o fa-2x"></i>
                </a>
            </td>
        </tr>
    }

</table>

@Scripts.Render("~/bundles/jquery")

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Excluir Veterinário</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o Veterinário?
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-primary">Não</button>
                <button id="btnContinueDelete" type="button" class="btn btn-danger">Sim</button>
            </div>
        </div>
    </div>
</div>

<script>
    var path_to_delete;

    $(".deleteItem").click(function (e) {
        path_to_delete = $(this).data('path');
    });

    $('#btnContinueDelete').click(function () {
        window.location = path_to_delete;
    });

    setTimeout(clearText, 3000);
    function clearText() {
        $('#retorno').text('');
    }
</script>