GerenciamentoBovinos/Models/Bovino.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GerenciamentoBovinos.Models
{
    public class Bovino
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        public long Brinco { get; set; }

        public virtual Raca Raca { get; set; }
        [ForeignKey("Raca")]
        public long RacaId { get; set; }

        public virtual Fornecedor Fornecedor { get; set; }
        [ForeignKey("Fornecedor")]
        public long FornecedorId { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public decimal Peso { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [Display(Name = "Data Nascimento")]
        public DateTime DtNascimento { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [Display(Name = "Vlr Unitário")]
        public decimal VlrUnitario { get; set; }

        [MaxLength(200, ErrorMessage = "A {0} deve ter no máximo {1} caracteres")]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
    }
}

GerenciamentoBovinos/Controllers/BovinoController.cs
using GerenciamentoBovinos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web.Mvc;

namespace GerenciamentoBovinos.Controllers
{
    [Authorize(Roles = "Sistema,Comercial,Administrativo")]
    public class BovinoController : Controller
    {
        private GerenciamentoContext db = new GerenciamentoContext();

        // GET: Bovino
        /// <summary>
        /// Retorna a lista de Bovinos cadastrados
        /// </summary>
        /// <param name="retorno"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Index(string retorno = null)
        {
            ViewBag.Retorno = retorno;
            var bovinos = db.Bovinos.Include(b => b.Raca);
            return View(bovinos.ToList());
        }

        // GET: Bovino/Create
        /// <summary>
        /// Gera a view para cadastrar um novo Bovino
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Create()
        {
            ViewBag.RacaId = new SelectList(db.Racas, "Id", "Nome");
            ViewBag.FornecedorId = new SelectList(db.Fornecedores, "Id", "Nome");
            return View();
        }

        // POST: Bovino/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Cadastra um novo Bovino
        /// </summary>
        /// <param name="bovino"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Brinco,RacaId,FornecedorId,Peso,DtNascimento,VlrUnitario,Descricao")] Bovino bovino)
        {
            if (ModelState.IsValid && bovino.RacaId > 0 && bovino.FornecedorId > 0)
            {
                Bovino validaBrinco = db.Bovinos.FirstOrDefault(x => x.Brinco == bovino.Brinco);

                if (validaBrinco != null)
                {
                    ModelState.AddModelError("Brinco", "Brinco já Cadastrado!");
                    ViewBag.RacaId = new SelectList(db.Racas, "Id", "Nome", bovino.RacaId);
                    ViewBag.FornecedorId = new SelectList(db.Fornecedores, "Id", "Nome", bovino.FornecedorId);
                    return View(bovino);
                }

                Confinamento confinamento = new Confinamento();
                confinamento.Bovino = bovino;
                confinamento.BovinoId = bovino.Id;
                confinamento.DtEntrada = DateTime.Now;
                confinamento.CustoTotal = bovino.VlrUnitario;
                confinamento.Vendido = false;
                db.Confinamentos.Add(confinamento);

                db.Bovinos.Add(bovino);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            Thread.Sleep(2000);
            ViewBag.RacaId = new SelectList(db.Racas, "Id", "Nome", bovino.RacaId);
            ViewBag.FornecedorId = new SelectList(db.Fornecedores, "Id", "Nome", bovino.FornecedorId);
            return View(bovino);
        }

        // GET: Bovino/Edit/5
        /// <summary>
        /// Gera a view para editar um Bovino
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bovino bovino = db.Bovinos.Find(id);
            if (bovino == null)
            {
                return HttpNotFound();
            }
            ViewBag.RacaId = new SelectList(db.Racas, "Id", "Nome", bovino.RacaId);
            ViewBag.FornecedorId = new SelectList(db.Fornecedores, "Id", "Nome", bovino.FornecedorId);
            return View(bovino);
        }

        // POST: Bovino/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edita um Bovino
        /// </summary>
        /// <param name="bovino"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Brinco,RacaId,FornecedorId,Peso,DtNascimento,VlrUnitario,Descricao")] Bovino bovino)
        {
            if (ModelState.IsValid)
            {
                var confinamento = db.Confinamentos.FirstOrDefault(b => b.BovinoId == bovino.Id);
                decimal vlrAnterior = db.Bovinos.FirstOrDefault(b => b.Id == bovino.Id).VlrUnitario;
                decimal vlrAtual = bovino.VlrUnitario;
                decimal retorno = 0;

                if (vlrAnterior < vlrAtual)
                {
                    retorno = vlrAtual - vlrAnterior;
                    confinamento.CustoTotal += retorno;
                }
                else if (vlrAnterior > vlrAtual)
                {
                    retorno = vlrAnterior - vlrAtual;
                    confinamento.CustoTotal -= retorno;
                }
                db.Entry(confinamento).State = EntityState.Modified;

                db.Set<Bovino>().AddOrUpdate(bovino);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RacaId = new SelectList(db.Racas, "Id", "Nome", bovino.RacaId);
            ViewBag.FornecedorId = new SelectList(db.Fornecedores, "Id", "Nome", bovino.FornecedorId);
            return View(bovino);
        }

        // GET: Bovino/Delete/5
        /// <summary>
        /// Exclui um Bovino
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Delete(long? id)
        {
            Bovino bovino = db.Bovinos.Find(id);

            List<ItemsVendaBovino> listaItemsVendaBovinos = db.ItemsVendaBovinos.Where(x => x.BovinoId == id).ToList();
            List<BaixaProduto> listaBaixaProdutos = db.BaixaProdutos.Where(x => x.BovinoId == id).ToList();
            List<Consulta> listaAtendimentos = db.Consultas.Where(x => x.BovinoId == id).ToList();

            if (listaItemsVendaBovinos != null && listaItemsVendaBovinos.Count > 0)
            {
                return RedirectToAction("Index", new { retorno = "Este Bovino esta relacionado a alguma venda de bovino cadastrada!" });
            }
            else if (listaBaixaProdutos != null && listaBaixaProdutos.Count > 0)
            {
                return RedirectToAction("Index", new { retorno = "Este Bovino esta relacionado a algum produto consumido em confinamento!" });
            }
            else if (listaAtendimentos != null && listaAtendimentos.Count > 0)
            {
                return RedirectToAction("Index", new { retorno = "Este Bovino esta relacionado a algum atendimento cadastrado!" });
            }

            if (bovino != null)
            {
                db.Bovinos.Remove(bovino);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return new HttpNotFoundResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GerenciamentoBovinos/Views/Bovino/Create.cshtml
@model GerenciamentoBovinos.Models.Bovino

@{
    ViewBag.Title = "Cadastrar Bovino";
}

<h2 class="text-center">Cadastrar Bovino</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Brinco, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Brinco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brinco, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.RacaId, "Raça", htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.DropDownList("RacaId", null, htmlAttributes: new { @class = "form-control" })
                <label class="text-danger" id="validaRaca"></label>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" , @onkeypress = "validate(event)" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.DtNascimento, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(model => model.DtNascimento, new { type = "date", @class = "form-control", id = "dtNasc" })
                @Html.ValidationMessageFor(model => model.DtNascimento, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.VlrUnitario, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.VlrUnitario, new { htmlAttributes = new { @class = "form-control", @onkeypress = "validate(event)" } })
                @Html.ValidationMessageFor(model => model.VlrUnitario, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.FornecedorId, "Fornecedor", htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.DropDownList("FornecedorId", null, htmlAttributes: new { @class = "form-control" })
                <label class="text-danger" id="validaFornecedor"></label>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextAreaFor(model => model.Descricao, new { @class = "col-md-12 form-control", rows = "4" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
                <input type="submit" value="Salvar" class="btn btn-success" onclick="validaDropDown();" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
}

<script>
    document.getElementById("dtNasc").valueAsDate = new Date();

    function validaDropDown() {
        var raca = $("#RacaId").val();
        var fornecedor = $("#FornecedorId").val();
        if (raca == null && fornecedor == null) {
            $("#validaRaca").text('Campo obrigatório.');
            $("#validaFornecedor").text('Campo obrigatório.');
            setTimeout(clearText, 2000);
        }
        else if (raca == null) {
            $("#validaRaca").text('Campo obrigatório.');
            setTimeout(clearText, 2000);
        }
        else if (fornecedor == null) {
            $("#validaFornecedor").text('Campo obrigatório.');
            setTimeout(clearText, 2000);
        }
    }

    function clearText() {
        $('#validaRaca').text('');
        $('#validaFornecedor').text('');
    }
</script>

GerenciamentoBovinos/Views/Bovino/Edit.cshtml
@model GerenciamentoBovinos.Models.Bovino

@{
    ViewBag.Title = "Editar Bovino";
}

<h2 class="text-center">Editar Bovino</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Brinco, "Brinco", htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Brinco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brinco, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.RacaId, "Raça", htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.DropDownList("RacaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RacaId, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" , @onkeypress = "validate(event)"} })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.DtNascimento, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextBoxFor(Model => Model.DtNascimento, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                @Html.ValidationMessageFor(model => model.DtNascimento, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.VlrUnitario, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.EditorFor(model => model.VlrUnitario, new { htmlAttributes = new { @class = "form-control" ,@onkeypress = "validate(event)" } })
                @Html.ValidationMessageFor(model => model.VlrUnitario, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.FornecedorId, "Fornecedor", htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.DropDownList("FornecedorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FornecedorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-10" })
                @Html.TextAreaFor(model => model.Descricao, new { @class = "col-md-12 form-control", rows = "4" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-danger" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
}

GerenciamentoBovinos/Views/Bovino/Index.cshtml
@model IEnumerable<GerenciamentoBovinos.Models.Bovino>

@{
    ViewBag.Title = "Lista de Bovinos";
    string retornoDelete = ViewBag.Retorno;
}

<h2 class="text-center">Lista de Bovinos</h2>

<p>
    @Html.ActionLink("Comprar", "Create", null, new { @class = "btn btn-secondary" })
</p>

<p class="text-danger" id="retorno">@retornoDelete</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brinco)
        </th>
        <th>
            @Html.Raw("Raça")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.Raw("Ações")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Brinco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raca.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Bovino", new { id = item.Id})">
                    <i class="fa fa-pencil-square-o fa-2x"></i>
                </a>
                <a id="deleteItem" class="deleteItem ml-2" href="#" style="color:red" data-target="#myModal" data-toggle="modal" data-path="@Url.Action("Delete", "Bovino", new { id = @item.Id })">
                    <i class="fa fa-trash-o fa-2x"></i>
                </a>
            </td>
        </tr>
    }

</table>

@Scripts.Render("~/bundles/jquery")

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Excluir Bovino</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o Bovino?
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-primary">Não</button>
                <button id="btnContinueDelete" type="button" class="btn btn-danger">Sim</button>
            </div>
        </div>
    </div>
</div>

<script>
    var path_to_delete;

    $(".deleteItem").click(function (e) {
        path_to_delete = $(this).data('path');
    });

    $('#btnContinueDelete').click(function () {
        window.location = path_to_delete;
    });
</script>